= CSS Documentation

This document provides an overview of the CSS styles used for content styling.

== What do I mean by content styling?

Content in this case refers to all of the nuts and bolts generated by curriculum developers to form a lesson or a course. It can also refer to templates or snippets that are re-used to stitch that custom content together.

== What do I *not* mean by content styling?

We are not focused on the outer 'wrappers' that hold these pieces of content. For instance - a webpage with a standard #Home, #Contact, Headers, Footers, Navigations, etc. These wrappers are styled too, and we have to ensure we can integrate our content styles with the wrapper styles so as not to clash, but we don't own wrappers or style them here.

== Structure

Our CSS is organized in a very loose 6-1 version of a https://sass-guidelin.es/#the-7-1-pattern[7-1 pattern]:

Abstracts:: tools and helpers used across the styles. This includes global functions, mixins, placeholders, etc.

Components:: Styles related to reusable components, such as headings, buttons, code snippets, etc.

Base:: Standard styles for commonly used elements. A boilerplate, if you will.

Layout:: Where applicable, this contains styles that pertain to a particular layout 'piece' of a puzzle. Because of the nature of our work (see 'What do I mean / not mean by content styling') we don't typically hit layout problems. Right now this only contains a lonely header template used to create prettier slide decks. The <style> element has been moved out of the --pdf-header-template HTML and placed here.

Pages:: Covers styles to build particular pages or sections of content.

Themes:: Usually themes are going to let you toggle a single application into multiple 'views'. That's kind of what's happening here - for instance this contains light and dark themes. But it also contains e-reader specific themes such as 'calibre-light.scss' which helps us compile a single ePub css file that works in multiple places.

Modes:: Here we are using the modes to hold styles that directly relate to particular modalities: ePub, PDF, slides, XHTML. These are the actual scss files that should be called in by sk directly. All other items will be imported.

Normally in a 7-1 pattern, pieces from the seven folders are called by a main.scss file. Since we are supporting multiple modalities, each .scss file located in Modes acts as it's own "main.scss" file depending on what our tooling is trying to build. So this is 6-1 where the six folders are called in by one of the modes.

== Other stuff

Archived:: Old stuff that we don't necessarily want to dump out of the repo yet.

Cover:: Templates used to build standardized image based pages, like a cover

Fonts:: TTF versions of the fonts used across all languages

== Maintenance Guidelines

- Avoid excessive nesting to keep our styles maintainable. At most consider 3 levels deep.
